FROM hpccsystems/hpcc:7.2.14-1

EXPOSE 8010 8002 8015 9876

COPY docker-entrypoint.sh /

RUN \
  sed -i 's/useDropZoneRestriction=true/useDropZoneRestriction=false/g' /etc/HPCCSystems/environment.conf

ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["/usr/sbin/sshd", "-D"]
