version: '3.2'
services:
  hpcc-master:
    build:
      context: .
      dockerfile: Dockerfile.hpcc
    image: adaptrislabs/hpcc-master:latest
    hostname: hpcc-master
    container_name: hpcc-master
    ports:
      - "8010:8010"
      - "8002:8002"
      - "8015:8015"
      - "9876:9876"

  interlok:
    image: adaptrislabs/interlok-hpcc:latest
    container_name: interlok
    hostname: interlok
    ports:
     - "5555:5555"
     - "8080:8080"
    environment:
     - HPCC_HOST=hpcc-master
     - INTERLOK_HOST=interlok
    depends_on:
      - hpcc-master
    links:
      - hpcc-master:hpcc-master
