version: '3.2'
services:
  hpcc-master:
    build:
      context: .
      dockerfile: Dockerfile.hpcc
    image: adaptrislabs/hpcc-master:latest
    hostname: hpcc-master
    container_name: hpcc-master
    ports:
      - "8010:8010"
      - "8002:8002"
      - "8015:8015"
      - "9876:9876"
  hpcc-localstack:
    image: localstack/localstack
    hostname: hpcc-localstack
    container_name: hpcc-localstack
    environment:
      - SERVICES=s3
      - USE_SSL=1
      - AWS_ACCESS_KEY_ID=abc
      - AWS_SECRET_ACCESS_KEY=def
    ports:
      - "4566:4566"
    volumes:
      - ./src/test/scripts:/docker-entrypoint-initaws.d

  interlok:
    image: adaptrislabs/interlok-hpcc:latest
    container_name: interlok
    hostname: interlok
    ports:
     - "5555:5555"
     - "8080:8080"
    environment:
     - HPCC_HOST=hpcc-master
     - INTERLOK_HOST=interlok
     - AWS_S3_ENDPOINT=http://hpcc-localstack:4566
     - AWS_BUCKET=localstack-bucket
     - AWS_ACCESS_KEY=Dummy Key
     - AWS_SECRET_KEY=Dummy Secret
     - AWS_REGION=eu-west-1
    depends_on:
      - hpcc-master
      - hpcc-localstack
    links:
      - hpcc-master:hpcc-master
      - hpcc-localstack:hpcc-localstack
